### ISSUE TITLE
make install fails on ubuntu 14.04: /etc/man.conf': No such file or directory

### ISSUE THREAD

**Issue by cweiske** [JIghtuse/manpages-tldr#4]
There are no installation instructions, so I thought "make install" should do it. But I get:

```
manpages-tldr$ LC_ALL=C sudo make install
Installing 'tldr' Man section
cp -n /etc/man.conf /etc/man.conf.bak
cp: cannot stat '/etc/man.conf': No such file or directory
make: *** [install] Error 1
```

This should not happen.

**Comment by JIghtuse** [comment]
@cweiske thanks for reporting! Actually, Makefile for this project is too naive and tied to Debian config files. Will fix it asap.

**Comment by JIghtuse** [comment]
Ah, looks like this comes from #1. It actually works for me without modifying `/etc/man.conf`, so I'm reverting some changes from that PR.

**Comment by JIghtuse** [comment]
Should be fixed by https://github.com/JIghtuse/manpages-tldr/commit/b0ee033359c2f1008acdaac631c0392e689af21e

**Comment by cweiske** [comment]
now it installs the man pages under `/`, because `MAN_DIR` is not available. Also, "make install" should copy, not symlink it.

**Comment by JIghtuse** [comment]
@cweiske whoops, my bad. Didn't test it enough.

**Comment by JIghtuse** [comment]
Now `make install` should copy manpages properly. We probably want to copy them to `/usr/local/share/man` though. Also, we still need to tell `man` that `*.tldr` files are manpages. I need to read about `/etc/man.conf`.

**Comment by JIghtuse** [comment]
Hm, looks like these man config file can have a different name on different distros. Debian now has `/etc/manpath.config`, while Fedora has `/etc/man_db.conf`.

I found a way to avoid modifications to system files. If you call `man` with a flag `-s`, it can find our manpages:

    man -s tldr sed

We can recommend creating an alias for this to simplify usage:

    alias tldr='man -s tldr'

@cweiske can you please check installation and usage now? I'll add this to README then.

**Comment by cweiske** [comment]
Works fine on Ubuntu 14.04.

**Comment by JIghtuse** [comment]
Great! Thanks for this issue and a feedback.
I'll update pages soon (will synchronize them with https://github.com/tldr-pages/tldr).
